# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'anapencere_python.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets 
from PyQt5.QtWidgets import QWidget, QInputDialog, QFileDialog

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(704, 659)
        MainWindow.setStyleSheet("\n"
"border-image: url(:/newPrefix/10121616457778.jpg);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(120, 90, 481, 471))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.widget.setFont(font)
        self.widget.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.widget.setObjectName("widget")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(50, 120, 47, 13))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);\n"
"")
        self.label_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(50, 240, 71, 16))
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.label_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_4.setObjectName("label_4")
        self.lineEdit_turbin = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_turbin.setGeometry(QtCore.QRect(220, 200, 101, 20))
        self.lineEdit_turbin.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lineEdit_turbin.setStyleSheet("border-image: url(:/newPrefix/orig.webp);\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(255, 255, 255, 255), stop:0.495 rgba(255, 255, 255, 255), stop:0.505 rgba(255, 0, 0, 255), stop:1 rgba(255, 0, 0, 255));\n"
"")
        self.lineEdit_turbin.setText("")
        self.lineEdit_turbin.setObjectName("lineEdit_turbin")
        self.filename = QtWidgets.QLineEdit(self.widget)
        self.filename.setGeometry(QtCore.QRect(220, 280, 231, 20))
        self.filename.setStyleSheet("border-image: url(:/newPrefix/orig.webp);")
        self.filename.setObjectName("filename")
        self.comboBox_santral = QtWidgets.QComboBox(self.widget)
        self.comboBox_santral.setGeometry(QtCore.QRect(220, 110, 141, 22))
        self.comboBox_santral.setStyleSheet("border-image: url(:/newPrefix/orig.webp);\n"
"color: rgb(0, 0, 0);")
        self.comboBox_santral.setObjectName("comboBox_santral")
        self.comboBox_santral.addItem("")
        self.comboBox_santral.addItem("")
        self.comboBox_santral.addItem("")
        self.comboBox_santral.addItem("")
        self.comboBox_santral.addItem("")
        self.comboBox_santral.addItem("")
        self.comboBox_santral.addItem("")
        self.comboBox_santral.addItem("")
        self.comboBox_santral.addItem("")
        self.comboBox_santral.addItem("")
        self.comboBox_santral.addItem("")
        self.filename_2 = QtWidgets.QLineEdit(self.widget)
        self.filename_2.setGeometry(QtCore.QRect(220, 320, 231, 20))
        self.filename_2.setStyleSheet("border-image: url(:/newPrefix/orig.webp);")
        self.filename_2.setObjectName("filename_2")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(50, 160, 47, 13))
        self.label_5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.label_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_5.setLineWidth(4)
        self.label_5.setScaledContents(False)
        self.label_5.setObjectName("label_5")
        self.comboBox_sehir = QtWidgets.QComboBox(self.widget)
        self.comboBox_sehir.setGeometry(QtCore.QRect(220, 160, 141, 22))
        self.comboBox_sehir.setAccessibleName("")
        self.comboBox_sehir.setStyleSheet("border-image: url(:/newPrefix/orig.webp);\n"
"color: rgb(0, 0, 0);")
        self.comboBox_sehir.setObjectName("comboBox_sehir")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.comboBox_sehir.addItem("")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(50, 200, 141, 16))
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.label_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_6.setObjectName("label_6")
        self.lineEdit_turbin_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_turbin_2.setGeometry(QtCore.QRect(220, 240, 101, 20))
        self.lineEdit_turbin_2.setStyleSheet("border-image: url(:/newPrefix/orig.webp);")
        self.lineEdit_turbin_2.setObjectName("lineEdit_turbin_2")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(180, 380, 75, 23))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"border-image: url(:/newPrefix/orig.webp);\n"
"border-color:black;")
        self.pushButton.setObjectName("pushButton")
        self.browse = QtWidgets.QPushButton(self.widget)
        self.browse.setGeometry(QtCore.QRect(50, 280, 75, 23))
        self.browse.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"border-image: url(:/newPrefix/orig.webp);\n"
"\n"
"border-color:black;")
        self.browse.setObjectName("browse")
        self.browse_2 = QtWidgets.QPushButton(self.widget)
        self.browse_2.setGeometry(QtCore.QRect(50, 320, 75, 23))
        self.browse_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"border-image: url(:/newPrefix/orig.webp);\n"
"\n"
"border-color:black;")
        self.browse_2.setObjectName("browse_2")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(160, 10, 201, 16))
        self.label.setStyleSheet("font: 75 italic 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);")
        self.label.setObjectName("label")
        self.label_2.raise_()
        self.label_4.raise_()
        self.filename.raise_()
        self.comboBox_santral.raise_()
        self.filename_2.raise_()
        self.label_5.raise_()
        self.comboBox_sehir.raise_()
        self.label_6.raise_()
        self.lineEdit_turbin_2.raise_()
        self.lineEdit_turbin.raise_()
        self.pushButton.raise_()
        self.browse.raise_()
        self.browse_2.raise_()
        self.label.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 704, 21))
        self.menubar.setObjectName("menubar")
        self.menuDosya = QtWidgets.QMenu(self.menubar)
        self.menuDosya.setObjectName("menuDosya")
        self.menuYard_m = QtWidgets.QMenu(self.menubar)
        self.menuYard_m.setObjectName("menuYard_m")
        MainWindow.setMenuBar(self.menubar)
        self.havadurumu = QtWidgets.QAction(MainWindow)
        self.havadurumu.setObjectName("havadurumu")
        self.uretimtahmini = QtWidgets.QAction(MainWindow)
        self.uretimtahmini.setObjectName("uretimtahmini")
        self.optimizasyon = QtWidgets.QAction(MainWindow)
        self.optimizasyon.setObjectName("optimizasyon")
        self.bizeulasin = QtWidgets.QAction(MainWindow)
        self.bizeulasin.setObjectName("bizeulasin")
        self.menuDosya.addAction(self.havadurumu)
        self.menuDosya.addAction(self.uretimtahmini)
        self.menuDosya.addAction(self.optimizasyon)
        self.menuYard_m.addAction(self.bizeulasin)
        self.menubar.addAction(self.menuDosya.menuAction())
        self.menubar.addAction(self.menuYard_m.menuAction())



        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
   

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Santral"))
        self.label_4.setText(_translate("MainWindow", "Panel Açısı"))
        self.comboBox_santral.setItemText(0, _translate("MainWindow", "Santral Seçiniz"))
        self.comboBox_santral.setItemText(1, _translate("MainWindow", "Yeni"))
        self.comboBox_santral.setItemText(2, _translate("MainWindow", "BANDIRMA I SANTRALİ"))
        self.comboBox_santral.setItemText(3, _translate("MainWindow", "BANDIRMA II SANTRALİ"))
        self.comboBox_santral.setItemText(4, _translate("MainWindow", "BALIKESİR SANTRALİ"))
        self.comboBox_santral.setItemText(5, _translate("MainWindow", "ÇANAKKALE SANTRALİ"))
        self.comboBox_santral.setItemText(6, _translate("MainWindow", "EFLATUN"))
        self.comboBox_santral.setItemText(7, _translate("MainWindow", "ERCİYES SANTRALİ"))
        self.comboBox_santral.setItemText(8, _translate("MainWindow", "HİPOKRAT"))
        self.comboBox_santral.setItemText(9, _translate("MainWindow", "KARABÜK SANTRALİ"))
        self.comboBox_santral.setItemText(10, _translate("MainWindow", "TUFANBEYLİ SANTRALİ"))
        self.label_5.setText(_translate("MainWindow", "Şehir"))
        self.comboBox_sehir.setItemText(0, _translate("MainWindow", "İl Seçiniz"))
        self.comboBox_sehir.setItemText(1, _translate("MainWindow", "ADANA"))
        self.comboBox_sehir.setItemText(2, _translate("MainWindow", "ADIYAMAN"))
        self.comboBox_sehir.setItemText(3, _translate("MainWindow", "AFYONKARAHİSAR"))
        self.comboBox_sehir.setItemText(4, _translate("MainWindow", "AĞRI"))
        self.comboBox_sehir.setItemText(5, _translate("MainWindow", "AMASYA"))
        self.comboBox_sehir.setItemText(6, _translate("MainWindow", "ANKARA"))
        self.comboBox_sehir.setItemText(7, _translate("MainWindow", "ANTALYA"))
        self.comboBox_sehir.setItemText(8, _translate("MainWindow", "ARTVİN"))
        self.comboBox_sehir.setItemText(9, _translate("MainWindow", "AYDIN"))
        self.comboBox_sehir.setItemText(10, _translate("MainWindow", "BALIKESİR"))
        self.comboBox_sehir.setItemText(11, _translate("MainWindow", "BİLECİK"))
        self.comboBox_sehir.setItemText(12, _translate("MainWindow", "BİNGÖL"))
        self.comboBox_sehir.setItemText(13, _translate("MainWindow", "BİTLİS"))
        self.comboBox_sehir.setItemText(14, _translate("MainWindow", "BOLU"))
        self.comboBox_sehir.setItemText(15, _translate("MainWindow", "BURDUR"))
        self.comboBox_sehir.setItemText(16, _translate("MainWindow", "BURSA"))
        self.comboBox_sehir.setItemText(17, _translate("MainWindow", "ÇANAKKALE"))
        self.comboBox_sehir.setItemText(18, _translate("MainWindow", "ÇANKIRI"))
        self.comboBox_sehir.setItemText(19, _translate("MainWindow", "ÇORUM"))
        self.comboBox_sehir.setItemText(20, _translate("MainWindow", "DENİZLİ"))
        self.comboBox_sehir.setItemText(21, _translate("MainWindow", "DİYARBAKIR"))
        self.comboBox_sehir.setItemText(22, _translate("MainWindow", "EDİRNE"))
        self.comboBox_sehir.setItemText(23, _translate("MainWindow", "ELAZIĞ"))
        self.comboBox_sehir.setItemText(24, _translate("MainWindow", "ERZİNCAN"))
        self.comboBox_sehir.setItemText(25, _translate("MainWindow", "ERZURUM"))
        self.comboBox_sehir.setItemText(26, _translate("MainWindow", "ESKİŞEHİR"))
        self.comboBox_sehir.setItemText(27, _translate("MainWindow", "GAZİANTEP"))
        self.comboBox_sehir.setItemText(28, _translate("MainWindow", "GİRESUN"))
        self.comboBox_sehir.setItemText(29, _translate("MainWindow", "GÜMÜŞHANE"))
        self.comboBox_sehir.setItemText(30, _translate("MainWindow", "HAKKARİ"))
        self.comboBox_sehir.setItemText(31, _translate("MainWindow", "HATAY"))
        self.comboBox_sehir.setItemText(32, _translate("MainWindow", "ISPARTA"))
        self.comboBox_sehir.setItemText(33, _translate("MainWindow", "MERSİN"))
        self.comboBox_sehir.setItemText(34, _translate("MainWindow", "İSTANBUL"))
        self.comboBox_sehir.setItemText(35, _translate("MainWindow", "İZMİR"))
        self.comboBox_sehir.setItemText(36, _translate("MainWindow", "KARS"))
        self.comboBox_sehir.setItemText(37, _translate("MainWindow", "KASTAMONU"))
        self.comboBox_sehir.setItemText(38, _translate("MainWindow", "KAYSERİ"))
        self.comboBox_sehir.setItemText(39, _translate("MainWindow", "KIRKLARELİ"))
        self.comboBox_sehir.setItemText(40, _translate("MainWindow", "KIRŞEHİR"))
        self.comboBox_sehir.setItemText(41, _translate("MainWindow", "KOCAELİ"))
        self.comboBox_sehir.setItemText(42, _translate("MainWindow", "KONYA"))
        self.comboBox_sehir.setItemText(43, _translate("MainWindow", "KÜTAHYA"))
        self.comboBox_sehir.setItemText(44, _translate("MainWindow", "MALATYA"))
        self.comboBox_sehir.setItemText(45, _translate("MainWindow", "MANİSA"))
        self.comboBox_sehir.setItemText(46, _translate("MainWindow", "KAHRAMANMARAŞ"))
        self.comboBox_sehir.setItemText(47, _translate("MainWindow", "MARDİN"))
        self.comboBox_sehir.setItemText(48, _translate("MainWindow", "MUĞLA"))
        self.comboBox_sehir.setItemText(49, _translate("MainWindow", "MUŞ"))
        self.comboBox_sehir.setItemText(50, _translate("MainWindow", "NEVŞEHİR"))
        self.comboBox_sehir.setItemText(51, _translate("MainWindow", "NİĞDE"))
        self.comboBox_sehir.setItemText(52, _translate("MainWindow", "ORDU"))
        self.comboBox_sehir.setItemText(53, _translate("MainWindow", "RİZE"))
        self.comboBox_sehir.setItemText(54, _translate("MainWindow", "SAKARYA"))
        self.comboBox_sehir.setItemText(55, _translate("MainWindow", "SAMSUN"))
        self.comboBox_sehir.setItemText(56, _translate("MainWindow", "SİİRT"))
        self.comboBox_sehir.setItemText(57, _translate("MainWindow", "SİNOP"))
        self.comboBox_sehir.setItemText(58, _translate("MainWindow", "SİVAS"))
        self.comboBox_sehir.setItemText(59, _translate("MainWindow", "TEKİRDAĞ"))
        self.comboBox_sehir.setItemText(60, _translate("MainWindow", "TOKAT"))
        self.comboBox_sehir.setItemText(61, _translate("MainWindow", "TRABZON"))
        self.comboBox_sehir.setItemText(62, _translate("MainWindow", "TUNCELİ"))
        self.comboBox_sehir.setItemText(63, _translate("MainWindow", "ŞANLIURFA"))
        self.comboBox_sehir.setItemText(64, _translate("MainWindow", "UŞAK"))
        self.comboBox_sehir.setItemText(65, _translate("MainWindow", "VAN"))
        self.comboBox_sehir.setItemText(66, _translate("MainWindow", "YOZGAT"))
        self.comboBox_sehir.setItemText(67, _translate("MainWindow", "ZONGULDAK"))
        self.comboBox_sehir.setItemText(68, _translate("MainWindow", "AKSARAY"))
        self.comboBox_sehir.setItemText(69, _translate("MainWindow", "BAYBURT"))
        self.comboBox_sehir.setItemText(70, _translate("MainWindow", "KARAMAN"))
        self.comboBox_sehir.setItemText(71, _translate("MainWindow", "KIRIKKALE"))
        self.comboBox_sehir.setItemText(72, _translate("MainWindow", "BATMAN"))
        self.comboBox_sehir.setItemText(73, _translate("MainWindow", "ŞIRNAK"))
        self.comboBox_sehir.setItemText(74, _translate("MainWindow", "BARTIN"))
        self.comboBox_sehir.setItemText(75, _translate("MainWindow", "ARDAHAN"))
        self.comboBox_sehir.setItemText(76, _translate("MainWindow", "IĞDIR"))
        self.comboBox_sehir.setItemText(77, _translate("MainWindow", "YALOVA"))
        self.comboBox_sehir.setItemText(78, _translate("MainWindow", "KARABÜK"))
        self.comboBox_sehir.setItemText(79, _translate("MainWindow", "KİLİS"))
        self.comboBox_sehir.setItemText(80, _translate("MainWindow", "OSMANİYE"))
        self.comboBox_sehir.setItemText(81, _translate("MainWindow", "DÜZCE"))
        self.label_6.setText(_translate("MainWindow", "RES Kurulu Güç (varsa)"))
        self.pushButton.setText(_translate("MainWindow", "Ekle"))
        self.browse.setText(_translate("MainWindow", "Browse"))
        self.browse_2.setText(_translate("MainWindow", "Browse"))
        self.label.setText(_translate("MainWindow", "SANTRAL TASARIMI"))
        self.menuDosya.setTitle(_translate("MainWindow", "Seçenekler"))
        self.menuYard_m.setTitle(_translate("MainWindow", "Yardım"))
        self.havadurumu.setText(_translate("MainWindow", "Hava Durumu Tahmini"))
        self.uretimtahmini.setText(_translate("MainWindow", "Üretim Tahmini"))
        self.optimizasyon.setText(_translate("MainWindow", "Optimizasyon"))
        self.bizeulasin.setText(_translate("MainWindow", "Bize Ulaşın"))

        self.browse.clicked.connect(self.browse_handler)        #dosya secimi icin buton basımı ayarladım
        self.browse_2.clicked.connect(self.browse_2_handler)



    def browse_handler(self):
        print("Button pressed")
        self.open_dialog_box()

    def browse_2_handler(self):
        print("Button pressed")
        self.open_dialog_box()

    def open_dialog_box(self):
        filename = QFileDialog.getOpenFileName()
        path = filename[0]

        print(path)

        with open(path, "r") as f:
            print(f.readline())
      


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

